[package]
name = "auth-service-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dotenv = "0.15"
mongodb = "2.0"
bcrypt = { version = "0.13", default-features = false, features = ["std"] }  # 🔥 Remove dependência desnecessária de zeroize 1.5
jsonwebtoken = "8"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1", features = ["v4", "serde"] }
solana-sdk = "1.16.27"
solana-client = "1.16.0"
bs58 = "0.4"  # Para converter a chave privada em base58
log = "0.4"               # 🟢 Biblioteca de logs
env_logger = "0.10"       # 🟢 Inicializador de logs
redis = { version = "0.22", features = ["tokio-comp", "connection-manager"] }
tokio = { version = "1", features = ["full"] }
tokio-native-tls = "0.3"
native-tls = "0.2"

[dependencies.zeroize]
version = "1.3"  # 🔥 FORÇA o uso da versão correta para evitar conflitos

[profile.dev]
debug = true

[profile.production]
inherits = "release"

